// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fghdfhprbnalybuducrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnaGRmaHByYm5hbHlidWR1Y3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODYxNTksImV4cCI6MjA2NzU2MjE1OX0.gBGV4zuXMxtUazUThYyYSazd1p-qif4WDR7N0QaYglg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});